import {
  FilterFieldBoolean, FilterFieldDate,
  FilterFieldPicklist,
  FilterFieldString,
  TableField,
} from '../interfaces/fields.interface';

export const baseFields: ((FilterFieldString | FilterFieldBoolean | FilterFieldPicklist | FilterFieldDate ) & TableField)[] = [
  {
    text: 'Blacklist attiva',
    frozen: false,
    value: 'is_blacklist_active',
    type: "boolean",
    widthGrow: 3,
    title: 'BL Attiva',
    field: 'is_blacklist_active',
    headerSort: true,
    formatter: 'boolean_dots',
    visible: true,
    hozAlign: 'center',
    headerHozAlign: 'center',
    emitEventOnSorting: true,
  },
  {
    text: 'ID',
    value: '_id',
    placeholder: 'ID',
    type: 'string',
    title: 'ID',
    field: '_id',
    headerSort: false,
    formatter: 'fonts',
    hozAlign: 'left',
    visible: false,
    emitEventOnSorting: true,
  },
  {
    text: 'Data inserimento',
    value: 'data_inserimento',
    placeholder: 'Data inserimento',
    type: 'date',
    datevalue: {
      labelstart: "Dal",
      labelend: "Al",
      dateFormat: "dd/MM/yyyy",
      dateOutputFormat: "yyyy-MM-dd",
    },
    title: 'Data inserimento',
    field: 'data_inserimento',
    headerSort: true,
    formatter: 'datetime',
    visible: true,
    hozAlign: 'left',
    emitEventOnSorting: true,
    formatterParams: {
      inputFormat: 'yyyy-MM-dd',
      outputFormat: 'dd/MM/yyyy',
      invalidPlaceholder: '-',
      timezone: 'Europe/Rome',
    },
  },
  {
    text: 'Data cancellazione',
    value: 'data_cancellazione',
    placeholder: 'Data cancellazione',
    type: 'date',
    datevalue: {
      labelstart: "Dal",
      labelend: "Al",
      dateFormat: "dd/MM/yyyy",
      dateOutputFormat: "yyyy-MM-dd",
    },
    title: 'Data cancellazione',
    field: 'data_cancellazione',
    headerSort: true,
    formatter: 'datetime',
    visible: true,
    hozAlign: 'left',
    emitEventOnSorting: true,
    formatterParams: {
      inputFormat: 'yyyy-MM-dd',
      outputFormat: 'dd/MM/yyyy',
      invalidPlaceholder: '',
      timezone: 'Europe/Rome',
    },
  },
  {
    text: 'Operatore forzatura',
    value: 'operatore_forzatura',
    placeholder: 'Operatore forzatura',
    type: 'string',
    title: 'Operatore forzatura',
    field: 'operatore_forzatura',
    headerSort: true,
    visible: true,
    hozAlign: 'left',
    emitEventOnSorting: true,
  },
  {
    text: 'Creato il',
    value: 'created_at',
    placeholder: 'Crato il',
    type: 'date',
    datevalue: {
      labelstart: "Dal",
      labelend: "Al",
      dateFormat: "dd/MM/yyyy",
      dateOutputFormat: "yyyy-MM-dd",
    },
    title: 'Creato il',
    field: 'created_at',
    headerSort: true,
    formatter: 'datetime',
    visible: true,
    hozAlign: 'left',
    emitEventOnSorting: true,
    formatterParams: {
      inputFormat: 'yyyy-MM-dd HH:mm',
      outputFormat: 'dd/MM/yyyy HH:mm',
      invalidPlaceholder: '',
      timezone: 'Europe/Rome',
    },
  }
];
